const fs = require('fs');
const path = require('path');

// Read the English file as the base
const englishPath = path.join(__dirname, 'src/i18n/locales/en.json');
const englishData = JSON.parse(fs.readFileSync(englishPath, 'utf8'));

// Language configurations with their target language codes
const languages = {
  fr: 'French',
  de: 'German',
  es: 'Spanish',
  ar: 'Arabic',
  hi: 'Hindi',
  zh: 'Chinese'
};

// Basic translation dictionaries for common terms
const basicTranslations = {
  fr: {
    "Loading...": "Chargement...",
    "Error": "Erreur",
    "Success": "Succès",
    "Cancel": "Annuler",
    "Save": "Enregistrer",
    "Delete": "Supprimer",
    "Edit": "Modifier",
    "Create": "Créer",
    "Update": "Mettre à jour",
    "Submit": "Soumettre",
    "Close": "Fermer",
    "Back": "Retour",
    "Next": "Suivant",
    "Previous": "Précédent",
    "Finish": "Terminer",
    "Continue": "Continuer",
    "Confirm": "Confirmer",
    "Yes": "Oui",
    "No": "Non",
    "OK": "OK",
    "Search": "Rechercher",
    "Filter": "Filtrer",
    "Sort": "Trier",
    "View": "Voir",
    "Download": "Télécharger",
    "Upload": "Téléverser",
    "Share": "Partager",
    "Copy": "Copier",
    "Home": "Accueil",
    "Dashboard": "Tableau de bord",
    "Settings": "Paramètres",
    "Profile": "Profil",
    "Help": "Aide",
    "About": "À propos",
    "Contact": "Contact",
    "Privacy": "Confidentialité",
    "Terms": "Conditions",
    "Logout": "Se déconnecter",
    "Login": "Se connecter",
    "Sign Up": "S'inscrire",
    "Sign In": "Se connecter",
    "Register": "S'inscrire",
    "Username": "Nom d'utilisateur",
    "Email": "E-mail",
    "Password": "Mot de passe",
    "Name": "Nom",
    "Title": "Titre",
    "Description": "Description",
    "Date": "Date",
    "Time": "Heure",
    "Status": "Statut",
    "Type": "Type",
    "Category": "Catégorie",
    "Score": "Score",
    "Points": "Points",
    "Level": "Niveau",
    "Progress": "Progrès",
    "Completed": "Terminé",
    "Language": "Langue",
    "Languages": "Langues",
    "User": "Utilisateur",
    "organization": "organisation",
    "Welcome back": "Bon retour",
    "Assignments": "Devoirs",
    "Assignment Gallery": "Galerie de Devoirs",
    "Certificates": "Certificats",
    "Admin": "Admin",
    "Management": "Gestion",
    "Users": "Utilisateurs",
    "Organizations": "Organisations"
  },
  de: {
    "Loading...": "Laden...",
    "Error": "Fehler",
    "Success": "Erfolg",
    "Cancel": "Abbrechen",
    "Save": "Speichern",
    "Delete": "Löschen",
    "Edit": "Bearbeiten",
    "Create": "Erstellen",
    "Update": "Aktualisieren",
    "Submit": "Senden",
    "Close": "Schließen",
    "Back": "Zurück",
    "Next": "Weiter",
    "Previous": "Vorherige",
    "Finish": "Beenden",
    "Continue": "Fortfahren",
    "Confirm": "Bestätigen",
    "Yes": "Ja",
    "No": "Nein",
    "OK": "OK",
    "Search": "Suchen",
    "Filter": "Filtern",
    "Sort": "Sortieren",
    "View": "Ansehen",
    "Download": "Herunterladen",
    "Upload": "Hochladen",
    "Share": "Teilen",
    "Copy": "Kopieren",
    "Home": "Startseite",
    "Dashboard": "Dashboard",
    "Settings": "Einstellungen",
    "Profile": "Profil",
    "Help": "Hilfe",
    "About": "Über",
    "Contact": "Kontakt",
    "Privacy": "Datenschutz",
    "Terms": "Bedingungen",
    "Logout": "Abmelden",
    "Login": "Anmelden",
    "Sign Up": "Registrieren",
    "Sign In": "Anmelden",
    "Register": "Registrieren",
    "Username": "Benutzername",
    "Email": "E-Mail",
    "Password": "Passwort",
    "Name": "Name",
    "Title": "Titel",
    "Description": "Beschreibung",
    "Date": "Datum",
    "Time": "Zeit",
    "Status": "Status",
    "Type": "Typ",
    "Category": "Kategorie",
    "Score": "Punktzahl",
    "Points": "Punkte",
    "Level": "Level",
    "Progress": "Fortschritt",
    "Completed": "Abgeschlossen",
    "Language": "Sprache",
    "Languages": "Sprachen",
    "User": "Benutzer",
    "organization": "Organisation",
    "Welcome back": "Willkommen zurück",
    "Assignments": "Aufgaben",
    "Assignment Gallery": "Aufgaben-Galerie",
    "Certificates": "Zertifikate",
    "Admin": "Admin",
    "Management": "Verwaltung",
    "Users": "Benutzer",
    "Organizations": "Organisationen"
  },
  es: {
    "Loading...": "Cargando...",
    "Error": "Error",
    "Success": "Éxito",
    "Cancel": "Cancelar",
    "Save": "Guardar",
    "Delete": "Eliminar",
    "Edit": "Editar",
    "Create": "Crear",
    "Update": "Actualizar",
    "Submit": "Enviar",
    "Close": "Cerrar",
    "Back": "Atrás",
    "Next": "Siguiente",
    "Previous": "Anterior",
    "Finish": "Finalizar",
    "Continue": "Continuar",
    "Confirm": "Confirmar",
    "Yes": "Sí",
    "No": "No",
    "OK": "OK",
    "Search": "Buscar",
    "Filter": "Filtrar",
    "Sort": "Ordenar",
    "View": "Ver",
    "Download": "Descargar",
    "Upload": "Subir",
    "Share": "Compartir",
    "Copy": "Copiar",
    "Home": "Inicio",
    "Dashboard": "Panel de Control",
    "Settings": "Configuración",
    "Profile": "Perfil",
    "Help": "Ayuda",
    "About": "Acerca de",
    "Contact": "Contacto",
    "Privacy": "Privacidad",
    "Terms": "Términos",
    "Logout": "Cerrar Sesión",
    "Login": "Iniciar Sesión",
    "Sign Up": "Registrarse",
    "Sign In": "Iniciar Sesión",
    "Register": "Registrarse",
    "Username": "Nombre de Usuario",
    "Email": "Correo Electrónico",
    "Password": "Contraseña",
    "Name": "Nombre",
    "Title": "Título",
    "Description": "Descripción",
    "Date": "Fecha",
    "Time": "Hora",
    "Status": "Estado",
    "Type": "Tipo",
    "Category": "Categoría",
    "Score": "Puntuación",
    "Points": "Puntos",
    "Level": "Nivel",
    "Progress": "Progreso",
    "Completed": "Completado",
    "Language": "Idioma",
    "Languages": "Idiomas",
    "User": "Usuario",
    "organization": "organización",
    "Welcome back": "Bienvenido de vuelta",
    "Assignments": "Tareas",
    "Assignment Gallery": "Galería de Tareas",
    "Certificates": "Certificados",
    "Admin": "Admin",
    "Management": "Gestión",
    "Users": "Usuarios",
    "Organizations": "Organizaciones"
  },
  hi: {
    "Loading...": "लोड हो रहा है...",
    "Error": "त्रुटि",
    "Success": "सफलता",
    "Cancel": "रद्द करें",
    "Save": "सेव करें",
    "Delete": "हटाएं",
    "Edit": "संपादित करें",
    "Create": "बनाएं",
    "Update": "अपडेट करें",
    "Submit": "जमा करें",
    "Close": "बंद करें",
    "Back": "वापस",
    "Next": "अगला",
    "Previous": "पिछला",
    "Finish": "समाप्त",
    "Continue": "जारी रखें",
    "Confirm": "पुष्टि करें",
    "Yes": "हां",
    "No": "नहीं",
    "OK": "ठीक है",
    "Search": "खोजें",
    "Filter": "फिल्टर",
    "Sort": "क्रमबद्ध करें",
    "View": "देखें",
    "Download": "डाउनलोड",
    "Upload": "अपलोड",
    "Share": "साझा करें",
    "Copy": "कॉपी",
    "Home": "होम",
    "Dashboard": "डैशबोर्ड",
    "Settings": "सेटिंग्स",
    "Profile": "प्रोफाइल",
    "Help": "सहायता",
    "About": "के बारे में",
    "Contact": "संपर्क",
    "Privacy": "गोपनीयता",
    "Terms": "नियम",
    "Logout": "लॉग आउट",
    "Login": "लॉग इन",
    "Sign Up": "साइन अप",
    "Sign In": "साइन इन",
    "Register": "रजिस्टर",
    "Username": "उपयोगकर्ता नाम",
    "Email": "ईमेल",
    "Password": "पासवर्ड",
    "Name": "नाम",
    "Title": "शीर्षक",
    "Description": "विवरण",
    "Date": "दिनांक",
    "Time": "समय",
    "Status": "स्थिति",
    "Type": "प्रकार",
    "Category": "श्रेणी",
    "Score": "स्कोर",
    "Points": "अंक",
    "Level": "स्तर",
    "Progress": "प्रगति",
    "Completed": "पूर्ण",
    "Language": "भाषा",
    "Languages": "भाषाएं",
    "User": "उपयोगकर्ता",
    "organization": "संगठन",
    "Welcome back": "वापसी पर स्वागत है",
    "Assignments": "असाइनमेंट",
    "Assignment Gallery": "असाइनमेंट गैलरी",
    "Certificates": "प्रमाणपत्र",
    "Admin": "एडमिन",
    "Management": "प्रबंधन",
    "Users": "उपयोगकर्ता",
    "Organizations": "संगठन"
  },
  ar: {
    "Loading...": "جاري التحميل...",
    "Error": "خطأ",
    "Success": "نجح",
    "Cancel": "إلغاء",
    "Save": "حفظ",
    "Delete": "حذف",
    "Edit": "تحرير",
    "Create": "إنشاء",
    "Update": "تحديث",
    "Submit": "إرسال",
    "Close": "إغلاق",
    "Back": "رجوع",
    "Next": "التالي",
    "Previous": "السابق",
    "Finish": "إنهاء",
    "Continue": "متابعة",
    "Confirm": "تأكيد",
    "Yes": "نعم",
    "No": "لا",
    "OK": "موافق",
    "Search": "بحث",
    "Filter": "تصفية",
    "Sort": "ترتيب",
    "View": "عرض",
    "Download": "تحميل",
    "Upload": "رفع",
    "Share": "مشاركة",
    "Copy": "نسخ",
    "Home": "الرئيسية",
    "Dashboard": "لوحة التحكم",
    "Settings": "الإعدادات",
    "Profile": "الملف الشخصي",
    "Help": "مساعدة",
    "About": "حول",
    "Contact": "اتصال",
    "Privacy": "الخصوصية",
    "Terms": "الشروط",
    "Logout": "تسجيل الخروج",
    "Login": "تسجيل الدخول",
    "Sign Up": "التسجيل",
    "Sign In": "تسجيل الدخول",
    "Register": "التسجيل",
    "Username": "اسم المستخدم",
    "Email": "البريد الإلكتروني",
    "Password": "كلمة المرور",
    "Name": "الاسم",
    "Title": "العنوان",
    "Description": "الوصف",
    "Date": "التاريخ",
    "Time": "الوقت",
    "Status": "الحالة",
    "Type": "النوع",
    "Category": "الفئة",
    "Score": "النتيجة",
    "Points": "النقاط",
    "Level": "المستوى",
    "Progress": "التقدم",
    "Completed": "مكتمل",
    "Language": "اللغة",
    "Languages": "اللغات",
    "User": "المستخدم",
    "organization": "المنظمة",
    "Welcome back": "مرحباً بعودتك",
    "Assignments": "المهام",
    "Assignment Gallery": "معرض المهام",
    "Certificates": "الشهادات",
    "Admin": "المدير",
    "Management": "الإدارة",
    "Users": "المستخدمون",
    "Organizations": "المنظمات"
  },
  zh: {
    "Loading...": "加载中...",
    "Error": "错误",
    "Success": "成功",
    "Cancel": "取消",
    "Save": "保存",
    "Delete": "删除",
    "Edit": "编辑",
    "Create": "创建",
    "Update": "更新",
    "Submit": "提交",
    "Close": "关闭",
    "Back": "返回",
    "Next": "下一个",
    "Previous": "上一个",
    "Finish": "完成",
    "Continue": "继续",
    "Confirm": "确认",
    "Yes": "是",
    "No": "否",
    "OK": "确定",
    "Search": "搜索",
    "Filter": "筛选",
    "Sort": "排序",
    "View": "查看",
    "Download": "下载",
    "Upload": "上传",
    "Share": "分享",
    "Copy": "复制",
    "Home": "首页",
    "Dashboard": "仪表板",
    "Settings": "设置",
    "Profile": "个人资料",
    "Help": "帮助",
    "About": "关于",
    "Contact": "联系",
    "Privacy": "隐私",
    "Terms": "条款",
    "Logout": "登出",
    "Login": "登录",
    "Sign Up": "注册",
    "Sign In": "登录",
    "Register": "注册",
    "Username": "用户名",
    "Email": "邮箱",
    "Password": "密码",
    "Name": "姓名",
    "Title": "标题",
    "Description": "描述",
    "Date": "日期",
    "Time": "时间",
    "Status": "状态",
    "Type": "类型",
    "Category": "类别",
    "Score": "分数",
    "Points": "积分",
    "Level": "级别",
    "Progress": "进度",
    "Completed": "已完成",
    "Language": "语言",
    "Languages": "语言",
    "User": "用户",
    "organization": "组织",
    "Welcome back": "欢迎回来",
    "Assignments": "作业",
    "Assignment Gallery": "作业库",
    "Certificates": "证书",
    "Admin": "管理员",
    "Management": "管理",
    "Users": "用户",
    "Organizations": "组织"
  }
};

// Function to recursively translate an object
function translateObject(obj, translations) {
  if (typeof obj === 'string') {
    return translations[obj] || obj;
  }

  if (Array.isArray(obj)) {
    return obj.map(item => translateObject(item, translations));
  }

  if (typeof obj === 'object' && obj !== null) {
    const result = {};
    for (const [key, value] of Object.entries(obj)) {
      result[key] = translateObject(value, translations);
    }
    return result;
  }

  return obj;
}

// Generate translation files for each language
console.log('Starting translation process...');

Object.entries(languages).forEach(([langCode, langName]) => {
  console.log(`Generating ${langName} (${langCode}) translations...`);

  const translations = basicTranslations[langCode] || {};
  const translatedData = translateObject(englishData, translations);

  const outputPath = path.join(__dirname, `src/i18n/locales/${langCode}.json`);
  fs.writeFileSync(outputPath, JSON.stringify(translatedData, null, 2), 'utf8');

  console.log(`✓ Generated ${langCode}.json`);
});

console.log('\n🎉 All translation files generated successfully!');
console.log('\nGenerated files:');
Object.keys(languages).forEach(langCode => {
  console.log(`  - src/i18n/locales/${langCode}.json`);
});
